@RiverBooks.Web_HostAddress = https://localhost:7279

GET {{RiverBooks.Web_HostAddress}}/books
Accept: application/json

###

@BookId = c3d6babd-c2c8-4fe8-a979-03e5f74f8a06
GET {{RiverBooks.Web_HostAddress}}/books/{{BookId}}
Accept: application/json

### 
POST {{RiverBooks.Web_HostAddress}}/books
Accept: application/json
Content-Type: application/json
{
  "id": "c3d6babd-c2c8-4fe8-a979-03e5f74f8a06",
  "title": "Modular Monoliths - Getting Started",
  "author": "Steve Smith",
  "price": 29.99
}

###
DELETE {{RiverBooks.Web_HostAddress}}/books/c3d6babd-c2c8-4fe8-a979-03e5f74f8a06
Accept: application/json

###
POST {{RiverBooks.Web_HostAddress}}/books/c3d6babd-c2c8-4fe8-a979-03e5f74f8a06/pricehistory
Accept: application/json
Content-Type: application/json
{
  "id": "c3d6babd-c2c8-4fe8-a979-03e5f74f8a06", 
  "newPrice": 9.99
}
###
POST {{RiverBooks.Web_HostAddress}}/users
Accept: application/json
Content-Type: application/json
{
  "email": "steve@test.com",
  "password": "Pass@word1"
}
###
POST {{RiverBooks.Web_HostAddress}}/users/login
Accept: application/json
Content-Type: application/json
{
  "email": "steve@test.com",
  "password": "Pass@word1"
}

###
@token=eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3NzIzOTA5NDIsIkVtYWlsQWRkcmVzcyI6InN0ZXZlQHRlc3QuY29tIiwiZXhwIjoxNzcyMzk0NTQyLCJuYmYiOjE3NzIzOTA5NDJ9._1dXwH28H1XjIFzrB3zfCoqICtbO1BOzOKBgHFsDWG4

###
POST {{RiverBooks.Web_HostAddress}}/cart
Accept: text/plain
Authorization: Bearer {{token}}
Content-Type: application/json
{
  "bookId": "c3d6babd-c2c8-4fe8-a979-03e5f74f8a06",
  "quantity": 1
}

### 
GET {{RiverBooks.Web_HostAddress}}/cart
Accept: application/json
Authorization: Bearer {{token}}